backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/uploads # Media files will be stored in the repo under static/images/uploads
public_folder: /uploads # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "static/_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "guide" # Used in routes, e.g., /admin/collections/blog
    label: "Guides" # Used in the UI
    folder: "static/_guides" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "select", options: ["Alliances", "Beginner", "Combat", "Commanders", "Events", "Inner City", "Lords", "Quests", "World Map"]}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "commander" # Used in routes, e.g., /admin/collections/blog
    label: "Commander" # Used in the UI
    folder: "static/_commanders" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Troop Type", name: "troop_type", widget: "select", options: ["Infantry", "Spearmen", "Cavalry", "Bowmen"]}
      - {label: "Type", name: "type", widget: "select", options: ["Tank","DPS", "Support"]}
      - {label: "Acquisition", name: "acquisition", widget: "select", options: ["Free", "Pay", "Not Available Yet"]}
      - name: image
        label: Image
        widget: object
        fields:
          - {name: src, label: Image, widget: image}
          - {name: alt, label: Alt text, widget: string}
          - {name: title, label: Title, widget: string}
      - {label: "Body", name: "body", widget: "markdown"}